language: R
sudo: false
cache: packages

before_script: 
  - export TZ=America/Sao_Paulo

env:
    global:
        - LANG=pt_BR.UTF-8
        - LC_ALL=pt_BR.UTF-8
        
script:
  - Rscript -e 'rmarkdown::render("index.Rmd")'
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: master
  on:
    branch: master

r_packages:
  - tidyverse
  - rmarkdown
  - flexdashboard

os:
  - linux
