language: R
sudo: false
cache: packages

before_script: 
  - export TZ=America/Sao_Paulo

env:
    global:
        - LANG=pt_BR.UTF-8
        - LC_ALL=pt_BR.UTF-8

r_packages:
  - tidyverse
  - rmarkdown
  - flexdashboard

os:
  - linux
